# Generated by Django 2.2.5 on 2019-09-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientsapp', '0002_auto_20190907_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',)},
        ),
    ]
